name: xinglian_vpn
description: 灵猫加速器 - Xboard 客户端
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  dio: ^5.8.0
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  path_provider: ^2.1.5
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
  web:
    generate: true
  image_path: assets/app_icon_store.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/app_icon_store.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/app_icon.png
    - assets/app_icon_store.png
